/*
 * Generated by Robotoworks Mechanoid
 */
package com.robotoworks.example.ghissues.ops;

import java.util.HashMap;

import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;
import com.robotoworks.mechanoid.ops.OperationConfiguration;

public abstract class AbstractGithubServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {
	
	private HashMap<String, OperationConfiguration> mOperationConfigurations;
	
	public AbstractGithubServiceOperationConfigurationRegistry() {
		
		mOperationConfigurations = new HashMap<String, OperationConfiguration>();
		
		registerOperationConfigurations();
	}
	
	protected void registerOperationConfigurations(){
		registerOperationConfiguration(GetIssuesForRepositoryOperation.ACTION_GET_ISSUES_FOR_REPOSITORY, new GetIssuesForRepositoryOperation.Configuration());
	}
	
	protected void registerOperationConfiguration(String action, OperationConfiguration config) {
		mOperationConfigurations.put(action, config);
	}

	@Override
	public OperationConfiguration getOperationConfiguration(String action) {
		return mOperationConfigurations.get(action);
	}
}
