/*
 * Generated by Robotoworks Mechanoid
 */
package com.robotoworks.example.movies.db.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMovieDBMigrationV2 extends SQLiteMigration {
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table table1 ( " +
			"_id integer " +
			") "
		);	
		db.execSQL(
			"create view view1 as select * from table1 "
		);	
		db.execSQL(
			"alter table table1 add column datstr text "
		);	
		db.execSQL(
			"drop view view1 "
		);	
		db.execSQL(
			"create view view1 as " +
			"select _id as _id, datstr as datstr from table1 "
		);	
	}
}
