/*
 * generated by Xtext
 */
package com.robotoworks.mechanoid.ops.ui.outline;

import com.robotoworks.mechanoid.ops.opServiceModel.Operation;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 */
public class OpServiceModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
    protected boolean _isLeaf(Operation modelElement) {
        return true;
    }
}
