/*
* generated by Xtext
*/
package com.robotoworks.mechanoid.db;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SqliteModelUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.robotoworks.mechanoid.db.ui.internal.SqliteModelActivator.getInstance().getInjector("com.robotoworks.mechanoid.db.SqliteModel");
	}
	
}
