/*
 * generated by Xtext
 */
package com.robotoworks.mechanoid.db.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class SqliteModelScopeProvider extends AbstractDeclarativeScopeProvider {
@Override
public IScope getScope(EObject context, EReference reference) {
	IScope scope = super.getScope(context, reference);
	
	return scope;
}


}
