/*
 * Generated by Robotoworks Mechanoid
 */
package com.mechanoid.db.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.sqlite.SQLiteMigration;

public abstract class AbstractTestDBMigrationV3 extends SQLiteMigration {
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table table_a ( " +
			"_id integer primary key autoincrement " +
			") "
		);
	}
}
