/*
 * Generated by Robotoworks Mechanoid
 */
package com.robotoworks.example.movies.ops;

public class MoviesService extends AbstractMoviesService {
    public MoviesService() {
        super(true);
    }
}
