/*
 * generated by Xtext
 */
package com.robotoworks.mechanoid.sqlite.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;


/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class SqliteModelProposalProvider extends
		AbstractSqliteModelProposalProvider {
	
	@Override
	public void completePrimaryExpression_Column(EObject model,
			Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completePrimaryExpression_Column(model, assignment, context, acceptor);
	}
}
