<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opServiceModel" nsURI="http://www.robotoworks.com/mechanoid/ops/OpServiceModel"
    nsPrefix="opServiceModel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" eType="#//ServiceBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ops" upperBound="-1" eType="#//Operation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//OperationArg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueClause" eType="#//UniqueClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationArg">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OpArgType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueClause"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OpArgType">
    <eLiterals name="Boolean" literal="boolean"/>
    <eLiterals name="String" value="1" literal="String"/>
    <eLiterals name="Integer" value="2" literal="int"/>
    <eLiterals name="Float" value="3" literal="float"/>
    <eLiterals name="Double" value="4" literal="double"/>
    <eLiterals name="Long" value="5" literal="long"/>
    <eLiterals name="Parcelable" value="6" literal="Parcelable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotUnique" eSuperTypes="#//UniqueClause"/>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueDeclaration" eSuperTypes="#//UniqueClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" unique="false" upperBound="-1"
        eType="#//OperationArg"/>
  </eClassifiers>
</ecore:EPackage>
